# Generated by Django 5.2.7 on 2025-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Можно указать ссылку на изображение вместо загрузки файла', null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
