# Generated by Django 5.2.7 on 2025-12-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления (минуты)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение блюда')),
                ('image_url', models.URLField(blank=True, help_text='Можно указать ссылку на изображение вместо загрузки файла', null=True, verbose_name='Ссылка на изображение')),
                ('author_name', models.CharField(default='Аноним', max_length=100, verbose_name='Имя автора')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email автора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
